// <auto-generated />
using System;
using CyberQuizGrupp1.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CyberQuizGrupp1.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260306140302_QuizRelationer")]
    partial class QuizRelationer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CyberQuizGrupp1.DAL.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CyberQuizGrupp1.SHARED.Models.AnswerOptionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId", "Text")
                        .IsUnique();

                    b.ToTable("AnswerOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsCorrect = true,
                            QuestionId = 1,
                            Text = "Ett försök att lura dig att lämna ut känslig information via falska meddelanden"
                        },
                        new
                        {
                            Id = 2,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "En metod för att kryptera filer på hårddisken"
                        },
                        new
                        {
                            Id = 3,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "Ett verktyg för att blockera nätverkstrafik"
                        },
                        new
                        {
                            Id = 4,
                            IsCorrect = true,
                            QuestionId = 2,
                            Text = "Avsändaradressen/domänen är misstänkt eller felstavad"
                        },
                        new
                        {
                            Id = 5,
                            IsCorrect = false,
                            QuestionId = 2,
                            Text = "Mejlet kommer alltid från en känd kontakt"
                        },
                        new
                        {
                            Id = 6,
                            IsCorrect = false,
                            QuestionId = 2,
                            Text = "Mejlet saknar alltid bilagor"
                        },
                        new
                        {
                            Id = 7,
                            IsCorrect = true,
                            QuestionId = 3,
                            Text = "Manipulation av människor för att få dem att göra något som gynnar angriparen"
                        },
                        new
                        {
                            Id = 8,
                            IsCorrect = false,
                            QuestionId = 3,
                            Text = "En portskanning av ett nätverk"
                        },
                        new
                        {
                            Id = 9,
                            IsCorrect = false,
                            QuestionId = 3,
                            Text = "En automatiserad lösenordsattack mot en server"
                        },
                        new
                        {
                            Id = 10,
                            IsCorrect = true,
                            QuestionId = 4,
                            Text = "Rapportera enligt rutin (IT/Helpdesk/SOC) och följ incidentprocessen"
                        },
                        new
                        {
                            Id = 11,
                            IsCorrect = false,
                            QuestionId = 4,
                            Text = "Skicka länken vidare så andra kan varna sig"
                        },
                        new
                        {
                            Id = 12,
                            IsCorrect = false,
                            QuestionId = 4,
                            Text = "Ignorera det och hoppas att inget händer"
                        },
                        new
                        {
                            Id = 13,
                            IsCorrect = true,
                            QuestionId = 5,
                            Text = "Att filtrera och kontrollera nätverkstrafik enligt regler"
                        },
                        new
                        {
                            Id = 14,
                            IsCorrect = false,
                            QuestionId = 5,
                            Text = "Att skapa nya lösenord åt användare"
                        },
                        new
                        {
                            Id = 15,
                            IsCorrect = false,
                            QuestionId = 5,
                            Text = "Att öka Wi-Fi-hastigheten"
                        },
                        new
                        {
                            Id = 16,
                            IsCorrect = true,
                            QuestionId = 6,
                            Text = "Att dela upp nätet i separata zoner för att begränsa spridning vid intrång"
                        },
                        new
                        {
                            Id = 17,
                            IsCorrect = false,
                            QuestionId = 6,
                            Text = "Att slå ihop alla nät till ett för enklare drift"
                        },
                        new
                        {
                            Id = 18,
                            IsCorrect = false,
                            QuestionId = 6,
                            Text = "Att kryptera all intern trafik automatiskt"
                        },
                        new
                        {
                            Id = 19,
                            IsCorrect = true,
                            QuestionId = 7,
                            Text = "Att tillåta all inkommande trafik från internet (0.0.0.0/0) till interna system"
                        },
                        new
                        {
                            Id = 20,
                            IsCorrect = false,
                            QuestionId = 7,
                            Text = "Att blockera en specifik port som inte används"
                        },
                        new
                        {
                            Id = 21,
                            IsCorrect = false,
                            QuestionId = 7,
                            Text = "Att logga nekad trafik för felsökning"
                        },
                        new
                        {
                            Id = 22,
                            IsCorrect = true,
                            QuestionId = 8,
                            Text = "Exponera bara det som behövs (minimera attackytan) och stäng resten"
                        },
                        new
                        {
                            Id = 23,
                            IsCorrect = false,
                            QuestionId = 8,
                            Text = "Öppna alla standardportar så tjänster fungerar direkt"
                        },
                        new
                        {
                            Id = 24,
                            IsCorrect = false,
                            QuestionId = 8,
                            Text = "Öppna portar temporärt utan loggning"
                        },
                        new
                        {
                            Id = 25,
                            IsCorrect = true,
                            QuestionId = 9,
                            Text = "WPA3 är säkrast (därefter WPA2); öppet Wi-Fi är minst säkert"
                        },
                        new
                        {
                            Id = 26,
                            IsCorrect = false,
                            QuestionId = 9,
                            Text = "Öppet Wi-Fi är säkrast eftersom det inte har lösenord"
                        },
                        new
                        {
                            Id = 27,
                            IsCorrect = false,
                            QuestionId = 9,
                            Text = "WPA2 är alltid osäkert och ska aldrig användas"
                        },
                        new
                        {
                            Id = 28,
                            IsCorrect = true,
                            QuestionId = 10,
                            Text = "WPS kan vara sårbart (t.ex. PIN-baserade attacker) och gör intrång enklare"
                        },
                        new
                        {
                            Id = 29,
                            IsCorrect = false,
                            QuestionId = 10,
                            Text = "WPS gör nätet snabbare men mindre stabilt"
                        },
                        new
                        {
                            Id = 30,
                            IsCorrect = false,
                            QuestionId = 10,
                            Text = "WPS krävs för att kunna använda WPA3"
                        },
                        new
                        {
                            Id = 31,
                            IsCorrect = true,
                            QuestionId = 11,
                            Text = "Ett falskt Wi-Fi-nät som imiterar ett legitimt för att få dig att ansluta"
                        },
                        new
                        {
                            Id = 32,
                            IsCorrect = false,
                            QuestionId = 11,
                            Text = "En attack där man gissar routerns admin-lösenord via Bluetooth"
                        },
                        new
                        {
                            Id = 33,
                            IsCorrect = false,
                            QuestionId = 11,
                            Text = "En teknik för att öka räckvidden på en router"
                        },
                        new
                        {
                            Id = 34,
                            IsCorrect = true,
                            QuestionId = 12,
                            Text = "Skapa ett separat gästnät (separat VLAN/isolering) med begränsad åtkomst"
                        },
                        new
                        {
                            Id = 35,
                            IsCorrect = false,
                            QuestionId = 12,
                            Text = "Låt gäster använda samma SSID och lösenord som interna nätet"
                        },
                        new
                        {
                            Id = 36,
                            IsCorrect = false,
                            QuestionId = 12,
                            Text = "Stäng av lösenord helt för att undvika support"
                        },
                        new
                        {
                            Id = 37,
                            IsCorrect = true,
                            QuestionId = 13,
                            Text = "Att skapa ett fingeravtryck (digest) för integritet/identifiering"
                        },
                        new
                        {
                            Id = 38,
                            IsCorrect = false,
                            QuestionId = 13,
                            Text = "Att göra data oläsbar och sedan läsbar igen med nyckel"
                        },
                        new
                        {
                            Id = 39,
                            IsCorrect = false,
                            QuestionId = 13,
                            Text = "Att komprimera data för att spara utrymme"
                        },
                        new
                        {
                            Id = 40,
                            IsCorrect = true,
                            QuestionId = 14,
                            Text = "Motstånd mot kollisioner (svårt att hitta två olika inputs med samma hash)"
                        },
                        new
                        {
                            Id = 41,
                            IsCorrect = false,
                            QuestionId = 14,
                            Text = "Att den alltid producerar olika längd på output"
                        },
                        new
                        {
                            Id = 42,
                            IsCorrect = false,
                            QuestionId = 14,
                            Text = "Att den går att reversera snabbt"
                        },
                        new
                        {
                            Id = 43,
                            IsCorrect = true,
                            QuestionId = 15,
                            Text = "För att göra rainbow tables och förberäknade attacker mycket svårare"
                        },
                        new
                        {
                            Id = 44,
                            IsCorrect = false,
                            QuestionId = 15,
                            Text = "För att kryptera lösenordet så det går att läsa tillbaka"
                        },
                        new
                        {
                            Id = 45,
                            IsCorrect = false,
                            QuestionId = 15,
                            Text = "För att minska längden på lösenordet i databasen"
                        },
                        new
                        {
                            Id = 46,
                            IsCorrect = true,
                            QuestionId = 16,
                            Text = "Hashning är envägs; kryptering är tvåvägs med nyckel"
                        },
                        new
                        {
                            Id = 47,
                            IsCorrect = false,
                            QuestionId = 16,
                            Text = "Hashning ger alltid längre output än kryptering"
                        },
                        new
                        {
                            Id = 48,
                            IsCorrect = false,
                            QuestionId = 16,
                            Text = "Hashning kräver alltid en privat nyckel"
                        },
                        new
                        {
                            Id = 49,
                            IsCorrect = true,
                            QuestionId = 17,
                            Text = "Symmetrisk använder samma nyckel; asymmetrisk använder publika/privata nycklar"
                        },
                        new
                        {
                            Id = 50,
                            IsCorrect = false,
                            QuestionId = 17,
                            Text = "Symmetrisk kräver certifikat; asymmetrisk gör inte det"
                        },
                        new
                        {
                            Id = 51,
                            IsCorrect = false,
                            QuestionId = 17,
                            Text = "Asymmetrisk är alltid snabbare än symmetrisk"
                        },
                        new
                        {
                            Id = 52,
                            IsCorrect = true,
                            QuestionId = 18,
                            Text = "AES"
                        },
                        new
                        {
                            Id = 53,
                            IsCorrect = false,
                            QuestionId = 18,
                            Text = "RSA"
                        },
                        new
                        {
                            Id = 54,
                            IsCorrect = false,
                            QuestionId = 18,
                            Text = "ECDSA"
                        },
                        new
                        {
                            Id = 55,
                            IsCorrect = true,
                            QuestionId = 19,
                            Text = "För att asymmetrisk är långsammare: man byter nycklar asymmetriskt och krypterar data symmetriskt"
                        },
                        new
                        {
                            Id = 56,
                            IsCorrect = false,
                            QuestionId = 19,
                            Text = "För att slippa nycklar helt"
                        },
                        new
                        {
                            Id = 57,
                            IsCorrect = false,
                            QuestionId = 19,
                            Text = "För att hashning inte fungerar utan hybrid"
                        },
                        new
                        {
                            Id = 58,
                            IsCorrect = true,
                            QuestionId = 20,
                            Text = "För att andra ska kunna kryptera till dig eller verifiera signaturer (beroende på användning)"
                        },
                        new
                        {
                            Id = 59,
                            IsCorrect = false,
                            QuestionId = 20,
                            Text = "För att dekryptera data som du själv krypterat med privat nyckel"
                        },
                        new
                        {
                            Id = 60,
                            IsCorrect = false,
                            QuestionId = 20,
                            Text = "För att generera slumpmässiga lösenord"
                        },
                        new
                        {
                            Id = 61,
                            IsCorrect = true,
                            QuestionId = 21,
                            Text = "Avlyssning och manipulation i transit (MITM) mellan klient och server"
                        },
                        new
                        {
                            Id = 62,
                            IsCorrect = false,
                            QuestionId = 21,
                            Text = "Att servern får virus från klienten"
                        },
                        new
                        {
                            Id = 63,
                            IsCorrect = false,
                            QuestionId = 21,
                            Text = "Att din hårddisk blir krypterad av ransomware"
                        },
                        new
                        {
                            Id = 64,
                            IsCorrect = true,
                            QuestionId = 22,
                            Text = "Ett dokument som binder en publik nyckel till en identitet, signerat av en CA"
                        },
                        new
                        {
                            Id = 65,
                            IsCorrect = false,
                            QuestionId = 22,
                            Text = "En engångskod för MFA"
                        },
                        new
                        {
                            Id = 66,
                            IsCorrect = false,
                            QuestionId = 22,
                            Text = "En brandväggsregel för port 443"
                        },
                        new
                        {
                            Id = 67,
                            IsCorrect = true,
                            QuestionId = 23,
                            Text = "Att webbläsaren litar på certifikat som kan härledas till en betrodd rot-CA"
                        },
                        new
                        {
                            Id = 68,
                            IsCorrect = false,
                            QuestionId = 23,
                            Text = "Att alla certifikat är självsignerade och lika säkra"
                        },
                        new
                        {
                            Id = 69,
                            IsCorrect = false,
                            QuestionId = 23,
                            Text = "Att DNS automatiskt validerar certifikatens äkthet"
                        },
                        new
                        {
                            Id = 70,
                            IsCorrect = true,
                            QuestionId = 24,
                            Text = "Webbläsaren varnar för ogiltigt/utgånget certifikat eller mismatch i domän"
                        },
                        new
                        {
                            Id = 71,
                            IsCorrect = false,
                            QuestionId = 24,
                            Text = "Webbsidan laddar snabbt"
                        },
                        new
                        {
                            Id = 72,
                            IsCorrect = false,
                            QuestionId = 24,
                            Text = "Låset syns alltid även på HTTP"
                        },
                        new
                        {
                            Id = 73,
                            IsCorrect = true,
                            QuestionId = 25,
                            Text = "För att angriparen behöver mer än en faktor (t.ex. lösenord + kod/enhet)"
                        },
                        new
                        {
                            Id = 74,
                            IsCorrect = false,
                            QuestionId = 25,
                            Text = "För att MFA gör lösenord onödiga och kan tas bort"
                        },
                        new
                        {
                            Id = 75,
                            IsCorrect = false,
                            QuestionId = 25,
                            Text = "För att MFA hindrar alla typer av phishing automatiskt"
                        },
                        new
                        {
                            Id = 76,
                            IsCorrect = true,
                            QuestionId = 26,
                            Text = "M4r!n#Kaktus_92Q"
                        },
                        new
                        {
                            Id = 77,
                            IsCorrect = false,
                            QuestionId = 26,
                            Text = "Sommar2026"
                        },
                        new
                        {
                            Id = 78,
                            IsCorrect = false,
                            QuestionId = 26,
                            Text = "password123"
                        },
                        new
                        {
                            Id = 79,
                            IsCorrect = true,
                            QuestionId = 27,
                            Text = "Att angripare testar läckta användarnamn/lösenord mot andra tjänster automatiskt"
                        },
                        new
                        {
                            Id = 80,
                            IsCorrect = false,
                            QuestionId = 27,
                            Text = "Att angripare gissar en PIN-kod på en telefon"
                        },
                        new
                        {
                            Id = 81,
                            IsCorrect = false,
                            QuestionId = 27,
                            Text = "Att angripare krypterar filer och kräver lösen"
                        },
                        new
                        {
                            Id = 82,
                            IsCorrect = true,
                            QuestionId = 28,
                            Text = "Använd en lösenordshanterare och unika långa lösenord per tjänst"
                        },
                        new
                        {
                            Id = 83,
                            IsCorrect = false,
                            QuestionId = 28,
                            Text = "Återanvänd samma lösenord men byt ofta"
                        },
                        new
                        {
                            Id = 84,
                            IsCorrect = false,
                            QuestionId = 28,
                            Text = "Skriv ner lösenord i en textfil på skrivbordet"
                        },
                        new
                        {
                            Id = 85,
                            IsCorrect = true,
                            QuestionId = 29,
                            Text = "Role-Based Access Control (åtkomst styrs av roller)"
                        },
                        new
                        {
                            Id = 86,
                            IsCorrect = false,
                            QuestionId = 29,
                            Text = "Rule-Based Authentication Control"
                        },
                        new
                        {
                            Id = 87,
                            IsCorrect = false,
                            QuestionId = 29,
                            Text = "Resource-Based Account Control"
                        },
                        new
                        {
                            Id = 88,
                            IsCorrect = true,
                            QuestionId = 30,
                            Text = "Ge bara de behörigheter som behövs för uppgiften – inte mer"
                        },
                        new
                        {
                            Id = 89,
                            IsCorrect = false,
                            QuestionId = 30,
                            Text = "Ge alla samma behörighet för enkelhetens skull"
                        },
                        new
                        {
                            Id = 90,
                            IsCorrect = false,
                            QuestionId = 30,
                            Text = "Ge alltid admin så problem löses snabbare"
                        },
                        new
                        {
                            Id = 91,
                            IsCorrect = true,
                            QuestionId = 31,
                            Text = "RBAC styr via roller; ABAC styr via attribut (t.ex. avdelning, plats, tid)"
                        },
                        new
                        {
                            Id = 92,
                            IsCorrect = false,
                            QuestionId = 31,
                            Text = "RBAC kräver alltid biometrisk inloggning; ABAC gör inte det"
                        },
                        new
                        {
                            Id = 93,
                            IsCorrect = false,
                            QuestionId = 31,
                            Text = "ABAC fungerar bara i Windows och RBAC bara i Linux"
                        },
                        new
                        {
                            Id = 94,
                            IsCorrect = true,
                            QuestionId = 32,
                            Text = "De har hög påverkan; komprometteras de kan angriparen få full kontroll"
                        },
                        new
                        {
                            Id = 95,
                            IsCorrect = false,
                            QuestionId = 32,
                            Text = "De kan inte loggas, så de är mindre spårbara"
                        },
                        new
                        {
                            Id = 96,
                            IsCorrect = false,
                            QuestionId = 32,
                            Text = "De har alltid kortare lösenord per standard"
                        },
                        new
                        {
                            Id = 97,
                            IsCorrect = true,
                            QuestionId = 33,
                            Text = "Ett sätt att hålla reda på en inloggad användares tillstånd mellan HTTP-anrop"
                        },
                        new
                        {
                            Id = 98,
                            IsCorrect = false,
                            QuestionId = 33,
                            Text = "En krypteringsalgoritm för lösenord"
                        },
                        new
                        {
                            Id = 99,
                            IsCorrect = false,
                            QuestionId = 33,
                            Text = "En brandväggsregel för att blockera cookies"
                        },
                        new
                        {
                            Id = 100,
                            IsCorrect = true,
                            QuestionId = 34,
                            Text = "Cookie är ofta lagring i klienten; token är en bärare av claims/åtkomst som kan lagras på olika sätt"
                        },
                        new
                        {
                            Id = 101,
                            IsCorrect = false,
                            QuestionId = 34,
                            Text = "Cookie är alltid krypterad; token är alltid okrypterad"
                        },
                        new
                        {
                            Id = 102,
                            IsCorrect = false,
                            QuestionId = 34,
                            Text = "Tokens kan bara användas i desktop-appar"
                        },
                        new
                        {
                            Id = 103,
                            IsCorrect = true,
                            QuestionId = 35,
                            Text = "Single Sign-On"
                        },
                        new
                        {
                            Id = 104,
                            IsCorrect = false,
                            QuestionId = 35,
                            Text = "Secure Sync Online"
                        },
                        new
                        {
                            Id = 105,
                            IsCorrect = false,
                            QuestionId = 35,
                            Text = "System Session Object"
                        },
                        new
                        {
                            Id = 106,
                            IsCorrect = true,
                            QuestionId = 36,
                            Text = "Stulen session kan användas längre (session hijacking) om den inte löper ut rimligt"
                        },
                        new
                        {
                            Id = 107,
                            IsCorrect = false,
                            QuestionId = 36,
                            Text = "Det gör alltid webbplatsen långsammare"
                        },
                        new
                        {
                            Id = 108,
                            IsCorrect = false,
                            QuestionId = 36,
                            Text = "Det gör att lösenord blir svagare automatiskt"
                        });
                });

            modelBuilder.Entity("CyberQuizGrupp1.SHARED.Models.CategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Nätverkssäkerhet"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Kryptografi & Säker kommunikation"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Identitet, Åtkomst & Autentisering (IAM)"
                        });
                });

            modelBuilder.Entity("CyberQuizGrupp1.SHARED.Models.QuestionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SubCategoryId", "Text")
                        .IsUnique();

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SubCategoryId = 1,
                            Text = "Vad är phishing?"
                        },
                        new
                        {
                            Id = 2,
                            SubCategoryId = 1,
                            Text = "Vilket är ett vanligt tecken på ett phishing-mejl?"
                        },
                        new
                        {
                            Id = 3,
                            SubCategoryId = 1,
                            Text = "Vad är social engineering?"
                        },
                        new
                        {
                            Id = 4,
                            SubCategoryId = 1,
                            Text = "Vad bör du göra om du klickat på en misstänkt länk på jobbet?"
                        },
                        new
                        {
                            Id = 5,
                            SubCategoryId = 2,
                            Text = "Vad är huvudsyftet med en brandvägg?"
                        },
                        new
                        {
                            Id = 6,
                            SubCategoryId = 2,
                            Text = "Vad innebär nätverkssegmentering?"
                        },
                        new
                        {
                            Id = 7,
                            SubCategoryId = 2,
                            Text = "Vilken regel är mest riskfylld i en brandvägg?"
                        },
                        new
                        {
                            Id = 8,
                            SubCategoryId = 2,
                            Text = "Vilken princip bör gälla för öppna portar ut mot internet?"
                        },
                        new
                        {
                            Id = 9,
                            SubCategoryId = 3,
                            Text = "Vilket är säkrast för ett hemnät: WPA3, WPA2 eller öppet Wi-Fi?"
                        },
                        new
                        {
                            Id = 10,
                            SubCategoryId = 3,
                            Text = "Varför är WPS ofta en säkerhetsrisk?"
                        },
                        new
                        {
                            Id = 11,
                            SubCategoryId = 3,
                            Text = "Vad är en 'evil twin'-attack?"
                        },
                        new
                        {
                            Id = 12,
                            SubCategoryId = 3,
                            Text = "Vilken åtgärd är bäst för gästnätverk?"
                        },
                        new
                        {
                            Id = 13,
                            SubCategoryId = 4,
                            Text = "Vad används en hashfunktion främst till?"
                        },
                        new
                        {
                            Id = 14,
                            SubCategoryId = 4,
                            Text = "Vilken egenskap är viktig för en säker hashfunktion?"
                        },
                        new
                        {
                            Id = 15,
                            SubCategoryId = 4,
                            Text = "Varför används 'salt' vid lagring av lösenord?"
                        },
                        new
                        {
                            Id = 16,
                            SubCategoryId = 4,
                            Text = "Varför räcker inte en hash som 'kryptering'?"
                        },
                        new
                        {
                            Id = 17,
                            SubCategoryId = 5,
                            Text = "Vad är skillnaden mellan symmetrisk och asymmetrisk kryptering?"
                        },
                        new
                        {
                            Id = 18,
                            SubCategoryId = 5,
                            Text = "Vilket är ett exempel på symmetrisk kryptering?"
                        },
                        new
                        {
                            Id = 19,
                            SubCategoryId = 5,
                            Text = "Varför används ofta hybridkryptografi?"
                        },
                        new
                        {
                            Id = 20,
                            SubCategoryId = 5,
                            Text = "Vad används en publik nyckel till?"
                        },
                        new
                        {
                            Id = 21,
                            SubCategoryId = 6,
                            Text = "Vad skyddar TLS (HTTPS) främst mot?"
                        },
                        new
                        {
                            Id = 22,
                            SubCategoryId = 6,
                            Text = "Vad är ett digitalt certifikat?"
                        },
                        new
                        {
                            Id = 23,
                            SubCategoryId = 6,
                            Text = "Vad betyder 'chain of trust' för certifikat?"
                        },
                        new
                        {
                            Id = 24,
                            SubCategoryId = 6,
                            Text = "Vilket är ett varningstecken i webbläsaren kopplat till TLS?"
                        },
                        new
                        {
                            Id = 25,
                            SubCategoryId = 7,
                            Text = "Varför är MFA säkrare än endast lösenord?"
                        },
                        new
                        {
                            Id = 26,
                            SubCategoryId = 7,
                            Text = "Vilket lösenord är starkast?"
                        },
                        new
                        {
                            Id = 27,
                            SubCategoryId = 7,
                            Text = "Vad är credential stuffing?"
                        },
                        new
                        {
                            Id = 28,
                            SubCategoryId = 7,
                            Text = "Vilken rekommendation är bäst för lösenordshantering?"
                        },
                        new
                        {
                            Id = 29,
                            SubCategoryId = 8,
                            Text = "Vad betyder RBAC?"
                        },
                        new
                        {
                            Id = 30,
                            SubCategoryId = 8,
                            Text = "Vad innebär principen om minsta privilegium (least privilege)?"
                        },
                        new
                        {
                            Id = 31,
                            SubCategoryId = 8,
                            Text = "Vad är skillnaden mellan RBAC och ABAC?"
                        },
                        new
                        {
                            Id = 32,
                            SubCategoryId = 8,
                            Text = "Varför är administratörskonton särskilt känsliga?"
                        },
                        new
                        {
                            Id = 33,
                            SubCategoryId = 9,
                            Text = "Vad är en session i webbsammanhang?"
                        },
                        new
                        {
                            Id = 34,
                            SubCategoryId = 9,
                            Text = "Vad är skillnaden mellan en cookie och en token?"
                        },
                        new
                        {
                            Id = 35,
                            SubCategoryId = 9,
                            Text = "Vad står SSO för?"
                        },
                        new
                        {
                            Id = 36,
                            SubCategoryId = 9,
                            Text = "Vad är en risk med för lång session-livslängd?"
                        });
                });

            modelBuilder.Entity("CyberQuizGrupp1.SHARED.Models.QuizAttemptModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("QuizAttempts");
                });

            modelBuilder.Entity("CyberQuizGrupp1.SHARED.Models.SubCategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId", "Name")
                        .IsUnique();

                    b.ToTable("SubCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            IsLocked = false,
                            Name = "Phishing & Social Engineering"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            IsLocked = true,
                            Name = "Brandväggar & Segmentering"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            IsLocked = true,
                            Name = "Wi-Fi & Trådlös säkerhet"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            IsLocked = false,
                            Name = "Hashning & Integritet"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            IsLocked = true,
                            Name = "Symmetrisk & Asymmetrisk kryptering"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            IsLocked = true,
                            Name = "TLS/HTTPS & Certifikat"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            IsLocked = false,
                            Name = "Lösenord & MFA"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            IsLocked = true,
                            Name = "RBAC/ABAC & Principer"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            IsLocked = true,
                            Name = "Sessions, Tokens & SSO"
                        });
                });

            modelBuilder.Entity("CyberQuizGrupp1.SHARED.Models.UserAnswerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("SelectedAnswerOptionId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SelectedAnswerOptionId");

                    b.HasIndex("AttemptId", "QuestionId")
                        .IsUnique();

                    b.ToTable("UserAnswers");
                });

            modelBuilder.Entity("CyberQuizGrupp1.SHARED.Models.UserResultModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("int");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("UserResults");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CyberQuizGrupp1.SHARED.Models.AnswerOptionModel", b =>
                {
                    b.HasOne("CyberQuizGrupp1.SHARED.Models.QuestionModel", "Question")
                        .WithMany("AnswerOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("CyberQuizGrupp1.SHARED.Models.QuestionModel", b =>
                {
                    b.HasOne("CyberQuizGrupp1.SHARED.Models.SubCategoryModel", "SubCategory")
                        .WithMany("Questions")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("CyberQuizGrupp1.SHARED.Models.QuizAttemptModel", b =>
                {
                    b.HasOne("CyberQuizGrupp1.SHARED.Models.SubCategoryModel", "SubCategory")
                        .WithMany("QuizAttempts")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("CyberQuizGrupp1.SHARED.Models.SubCategoryModel", b =>
                {
                    b.HasOne("CyberQuizGrupp1.SHARED.Models.CategoryModel", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CyberQuizGrupp1.SHARED.Models.UserAnswerModel", b =>
                {
                    b.HasOne("CyberQuizGrupp1.SHARED.Models.QuizAttemptModel", "Attempt")
                        .WithMany("UserAnswers")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CyberQuizGrupp1.SHARED.Models.QuestionModel", "Question")
                        .WithMany("UserAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CyberQuizGrupp1.SHARED.Models.AnswerOptionModel", "SelectedAnswerOption")
                        .WithMany("UserAnswers")
                        .HasForeignKey("SelectedAnswerOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Attempt");

                    b.Navigation("Question");

                    b.Navigation("SelectedAnswerOption");
                });

            modelBuilder.Entity("CyberQuizGrupp1.SHARED.Models.UserResultModel", b =>
                {
                    b.HasOne("CyberQuizGrupp1.SHARED.Models.SubCategoryModel", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CyberQuizGrupp1.DAL.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CyberQuizGrupp1.DAL.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CyberQuizGrupp1.DAL.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CyberQuizGrupp1.DAL.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CyberQuizGrupp1.SHARED.Models.AnswerOptionModel", b =>
                {
                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("CyberQuizGrupp1.SHARED.Models.CategoryModel", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("CyberQuizGrupp1.SHARED.Models.QuestionModel", b =>
                {
                    b.Navigation("AnswerOptions");

                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("CyberQuizGrupp1.SHARED.Models.QuizAttemptModel", b =>
                {
                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("CyberQuizGrupp1.SHARED.Models.SubCategoryModel", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("QuizAttempts");
                });
#pragma warning restore 612, 618
        }
    }
}
